dependencies:
  pandas: 2.3.3
  scikit-learn: 1.7.2
  seaborn: 0.13.2
  yaml_version: 6.0.3
model_metadata:
  best_score_cv: 0.9556836610737397
  hyperparameters:
    max_depth: null
    max_features: sqrt
    min_samples_leaf: 1
    min_samples_split: 2
    n_estimators: 300
  model_type: RandomForestClassifier
